{% set name = "kitty" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kovidgoyal/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 02e144d0a1d18b0d094c50108b782f7318d687f7080be0bbd707419f5551cb89

build:
  number: 0
  skip: true  # [win or py2k or osx]
  ignore_run_exports:
    - imagemagick

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
  host:
    - python
    - dbus  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-xineramaproto  # [linux]
    - libglu  # [linux]
    - xorg-glproto  # [linux]
    - mesalib  # [linux]
    - libxkbcommon  # [linux]
    # the following are listed as runtime deps, but seem to be needed at build
    - harfbuzz >=1.5.0
    - zlib
    - libpng
    - freetype  # [linux]
    - fontconfig  # [linux]
    - imagemagick
    - pygments
    - libcanberra
  run:
    - python
    - harfbuzz >=1.5.0
    - zlib
    - libpng
    - freetype  # [linux]
    - fontconfig  # [linux]
    - imagemagick
    - pygments
    - xkeyboard-config
    - libcanberra

test:
  commands:
    - kitty --help

about:
  home: https://sw.kovidgoyal.net/kitty/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A cross-platform, fast, feature full, GPU based terminal emulator
  doc_url: https://sw.kovidgoyal.net/kitty/
  dev_url: https://github.com/kovidgoyal/kitty

extra:
  recipe-maintainers:
    - scopatz
