travis:
  secure:
    BINSTAR_TOKEN: qBdxF+yIJnt0RvEOdagPMD4H/tA+chHRW0ShoFns8I8c5Q4gPzOJMw32XlHIwdyOE+4LXzz6Cd0m4BvnV2NJkBu217VrecsWY2YqcI110t5jdjMZOm+wxd4d93hRd/0nguYOEU/G6HDRtOAf8nJGKFkZI+hLEwo3xdcN/WjbW5QeXAgcMb8bocIoxbUMwM5gXGOtM7j6QJdTRuEiFGWjzELs1z0Y041kj9ixJ3NHCxW8Dy4oOoGsXB5FVNNNvMC+u+scbNzMiWceP8EQtTItZsJXqSqYTvzera0d//oHfquka6mf402b6HmYCccdHSUTmJiFBMmu/0V7TXh3GqPPyfpFbDOWTpKvkIvNB4CRGZzjuhRMvdW5II8GCsq+gtz/5+PXJ8GmQ8ZB848xIh99+NRWwNgVCEdIFahRUxZTz1H6MWT+EnZXovwGOTcqClqfYsfXV9thK++t3ZsoIVQX/WJkLVI+Ga5ajyNmmkH3YYZ6unMYEUFLAeADfazySvnhP4jxdCLcApc+xiCRXqhqGpA6+yVbyAo6CiKRS8jBM53BDOk92wjSsui9uVIlkEJtP3aqUv9HEFuGBEgfJqLXRPJGC0f+0ihlIES+qfciFwL5qmOb3uUWe9YHkrkIdbjsE1LhzbwMpqRmcYufAqHawlJewpg4C4P43AmZNFCnMUc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
